module.exports = {
  apps: [
    {
      name: "og-core",
      cwd: "./core",
      script: "dist/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 53666,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "logs/og-core-error.log",
      out_file: "logs/og-core-out.log",
      merge_logs: true,
    },
    {
      name: "og-dashboard-api",
      cwd: "./dashboard",
      script: "apps/api/dist/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 53667,
        WEB_ORIGIN: "https://www.openguardrails.com",
        OG_CORE_URL: "http://127.0.0.1:53666",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "logs/og-dashboard-api-error.log",
      out_file: "logs/og-dashboard-api-out.log",
      merge_logs: true,
    },
    {
      name: "og-dashboard-web",
      cwd: "./dashboard/apps/web",
      script: "node_modules/.bin/vite",
      args: "preview --port 53668 --host 127.0.0.1",
      env: {
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "256M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "logs/og-dashboard-web-error.log",
      out_file: "logs/og-dashboard-web-out.log",
      merge_logs: true,
    },
  ],
};
