"""OGR -> NVIDIA OpenShell adapter — the TEAM scenario.

OpenShell is a gateway + container/SSH sandbox for autonomous coding agents. Its
egress proxy evaluates every outbound connection against an **OPA/Rego** policy
(deny-by-default, L4 host:port + L7 HTTP inspection), credentials are injected at
the gateway and resolved by the proxy only for policy-allowed endpoints, and code
runs in an isolated Docker/K8s backend with resource limits.

Where srt secures ONE developer's laptop, OpenShell secures a SHARED, multi-tenant
deployment: central policy, central audit, hard container isolation. OGR is the
layer above — one `policy.json` is compiled here into the Rego the proxy enforces
and the sandbox config the supervisor launches, so a team manages security as data,
not as bespoke per-agent code.

NOTE: OpenShell's concrete config schema is not fully public; the sandbox-config
shape below is illustrative of the documented concepts (backend, resource limits,
credential endpoints). The Rego is real and runnable in OPA.
"""
from __future__ import annotations

import json
from textwrap import indent


def policy_to_rego(policy: dict, package: str = "ogr.egress") -> str:
    """Compile the OGR egress allowlist into a deny-by-default Rego policy the
    OpenShell proxy can evaluate for L4/L7 network decisions."""
    sb = policy.get("sandbox", {})
    allow = sb.get("egress_allowlist") or policy.get("config_rules", {}).get("egress_allowlist", [])
    deny = sb.get("deny_egress", [])

    allow_lines = ",\n".join(f'        "{d}"' for d in allow) or "        # (none)"
    deny_lines = ",\n".join(f'        "{d}"' for d in deny) or "        # (none)"

    return f"""# Generated by OGR from policy.json — do not edit by hand.
package {package}

import future.keywords.in

# deny-by-default: a connection is allowed only if its host matches the OGR
# egress allowlist and is not explicitly denied.
default allow := false

allowed_domains := {{
{allow_lines}
}}

denied_domains := {{
{deny_lines}
}}

allow if {{
    not denied(input.host)
    some pattern in allowed_domains
    host_matches(input.host, pattern)
}}

denied(host) if {{
    some pattern in denied_domains
    host_matches(host, pattern)
}}

# exact match, or "*.example.com" wildcard suffix match
host_matches(host, pattern) if host == pattern
host_matches(host, pattern) if {{
    startswith(pattern, "*.")
    suffix := substring(pattern, 1, -1)   # ".example.com"
    endswith(host, suffix)
}}
"""


def policy_to_sandbox_config(policy: dict) -> dict:
    """Illustrative OpenShell sandbox/gateway config derived from the OGR policy."""
    sb = policy.get("sandbox", {})
    limits = sb.get("resource_limits", {})
    return {
        "backend": "docker",                      # or "ssh" / "kubernetes"
        "image": "openshell/agent-sandbox:latest",
        "workspace": {
            "mount": "/workspace",
            "writable": sb.get("workspace_write", ["."]),
        },
        "network": {
            "default": "deny",
            "policy_engine": "opa",
            "rego_package": "ogr.egress",
            "proxy": "http-connect",
        },
        "filesystem": {
            "deny_read": sb.get("deny_read", []),
            "deny_write": sb.get("deny_write", []),
        },
        "resource_limits": {
            "cpus": limits.get("cpus", 2),
            "memory_mb": limits.get("memory_mb", 2048),
            "pids": limits.get("pids", 256),
        },
        # credentials live at the gateway; the proxy injects them only for
        # endpoints the Rego policy allows.
        "credential_endpoints": sb.get("egress_allowlist", []),
    }


def emit(policy: dict) -> tuple[str, dict]:
    """Return (rego_policy_text, sandbox_config_dict)."""
    return policy_to_rego(policy), policy_to_sandbox_config(policy)


def render(policy: dict) -> str:
    rego, cfg = emit(policy)
    return ("# --- ogr_egress.rego ---\n" + rego +
            "\n# --- sandbox.config.json ---\n" +
            json.dumps(cfg, indent=2) + "\n")
